import { Collection, Topic, Vocabulary } from './types';

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-toeic-essential',
    title: 'Từ vựng TOEIC Căn Bản',
    description: 'Bộ từ vựng TOEIC thông dụng cho luyện thi và giao tiếp công sở',
    icon: 'Briefcase',
  },
];

export const INITIAL_TOPICS: Topic[] = [
  {
    id: 'topic-office',
    collection_id: 'col-toeic-essential',
    title: 'Văn phòng & Công sở',
    description: 'Từ vựng chủ đề môi trường làm việc, thiết bị và công việc hàng ngày',
    icon: 'Building2',
  },
  {
    id: 'topic-business',
    collection_id: 'col-toeic-essential',
    title: 'Hội họp & Đàm phán',
    description: 'Các thuật ngữ thường gặp trong các buổi họp, hợp đồng và thương lượng',
    icon: 'Users',
  },
  {
    id: 'topic-travel',
    collection_id: 'col-toeic-essential',
    title: 'Du lịch & Di chuyển',
    description: 'Từ vựng công tác, khách sạn, vé máy bay và lịch trình chuyến đi',
    icon: 'Plane',
  },
];

export const INITIAL_VOCABULARIES: Vocabulary[] = [
  // Topic: Văn phòng & Công sở
  {
    id: 'vocab-contract',
    topic_id: 'topic-office',
    word: 'Contract',
    phonetic_uk: 'kənˈtrækt',
    phonetic_us: 'ˈkɑːntrækt',
    part_of_speech: 'noun',
    meaning: 'Hợp đồng, sự ký kết',
    example: 'Please sign the employment contract before starting your work.',
    example_translation: 'Vui lòng ký hợp đồng lao động trước khi bắt đầu công việc.',
    synonyms: 'Agreement, Compact, Settlement',
    collocations: 'Sign a contract, Breach of contract, Terminate a contract',
  },
  {
    id: 'vocab-colleague',
    topic_id: 'topic-office',
    word: 'Colleague',
    phonetic_uk: 'ˈkɒliːɡ',
    phonetic_us: 'ˈkɑːliːɡ',
    part_of_speech: 'noun',
    meaning: 'Đồng nghiệp',
    example: 'She collaborates closely with her colleagues on this major project.',
    example_translation: 'Cô ấy hợp tác chặt chẽ với các đồng nghiệp trong dự án lớn này.',
    synonyms: 'Coworker, Associate, Workmate',
    collocations: 'Work colleague, Trusted colleague, Former colleague',
  },
  {
    id: 'vocab-deadline',
    topic_id: 'topic-office',
    word: 'Deadline',
    phonetic_uk: 'ˈdedlaɪn',
    phonetic_us: 'ˈdedlaɪn',
    part_of_speech: 'noun',
    meaning: 'Hạn chót, thời hạn hoàn thành',
    example: 'We must work overtime to meet the project deadline.',
    example_translation: 'Chúng tôi phải làm thêm giờ để kịp hạn chót của dự án.',
    synonyms: 'Due date, Time limit, Cutoff',
    collocations: 'Meet a deadline, Tight deadline, Extend a deadline',
  },
  {
    id: 'vocab-executive',
    topic_id: 'topic-office',
    word: 'Executive',
    phonetic_uk: 'ɪɡˈzekjətɪv',
    phonetic_us: 'ɪɡˈzekjətɪv',
    part_of_speech: 'noun',
    meaning: 'Giám đốc điều hành, người quản lý cấp cao',
    example: 'The chief executive approved the new office budget.',
    example_translation: 'Giám đốc điều hành đã phê duyệt ngân sách văn phòng mới.',
    synonyms: 'Manager, Director, Administrator',
    collocations: 'Chief executive officer (CEO), Executive board',
  },

  // Topic: Hội họp & Đàm phán
  {
    id: 'vocab-negotiate',
    topic_id: 'topic-business',
    word: 'Negotiate',
    phonetic_uk: 'nɪˈɡəʊʃieɪt',
    phonetic_us: 'nɪˈɡoʊʃieɪt',
    part_of_speech: 'verb',
    meaning: 'Đàm phán, thương lượng',
    example: 'The managers met to negotiate a better deal for the company.',
    example_translation: 'Các quản lý đã gặp nhau để đàm phán một thỏa thuận tốt hơn cho công ty.',
    synonyms: 'Bargain, Discuss terms, Mediate',
    collocations: 'Negotiate a deal, Negotiate terms, Successfully negotiate',
  },
  {
    id: 'vocab-proposal',
    topic_id: 'topic-business',
    word: 'Proposal',
    phonetic_uk: 'prəˈpəʊzl',
    phonetic_us: 'prəˈpoʊzl',
    part_of_speech: 'noun',
    meaning: 'Đề xuất, bản kiến nghị',
    example: 'The team submitted a detailed proposal to the client.',
    example_translation: 'Đội ngũ đã đệ trình một bản đề xuất chi tiết tới khách hàng.',
    synonyms: 'Suggestion, Scheme, Offer',
    collocations: 'Submit a proposal, Business proposal, Draft a proposal',
  },
  {
    id: 'vocab-agenda',
    topic_id: 'topic-business',
    word: 'Agenda',
    phonetic_uk: 'əˈdʒendə',
    phonetic_us: 'əˈdʒendə',
    part_of_speech: 'noun',
    meaning: 'Chương trình nghị sự, nội dung cuộc họp',
    example: 'The first item on today’s agenda is the quarterly budget review.',
    example_translation: 'Mục đầu tiên trong chương trình nghị sự hôm nay là xem xét ngân sách quý.',
    synonyms: 'Schedule, Program, List of items',
    collocations: 'Set the agenda, On the agenda, Meeting agenda',
  },

  // Topic: Du lịch & Di chuyển
  {
    id: 'vocab-reservation',
    topic_id: 'topic-travel',
    word: 'Reservation',
    phonetic_uk: 'ˌrezəˈveɪʃn',
    phonetic_us: 'ˌrezərˈveɪʃn',
    part_of_speech: 'noun',
    meaning: 'Sự đặt chỗ trước',
    example: 'I made a hotel reservation for three nights in Tokyo.',
    example_translation: 'Tôi đã đặt phòng khách sạn 3 đêm tại Tokyo.',
    synonyms: 'Booking, Appointment',
    collocations: 'Make a reservation, Confirm a reservation, Cancel a reservation',
  },
  {
    id: 'vocab-itinerary',
    topic_id: 'topic-travel',
    word: 'Itinerary',
    phonetic_uk: 'aɪˈtɪnərəri',
    phonetic_us: 'aɪˈtɪnəreri',
    part_of_speech: 'noun',
    meaning: 'Lịch trình chuyến đi, hành trình',
    example: 'The travel agent sent us the complete travel itinerary.',
    example_translation: 'Đại lý du lịch đã gửi cho chúng tôi lịch trình chuyến đi hoàn chỉnh.',
    synonyms: 'Travel plan, Schedule, Route',
    collocations: 'Detailed itinerary, Travel itinerary, Change the itinerary',
  },
];
