import { CheckCircle2, Clock3, Trophy, XCircle } from 'lucide-react';
import type { SynonymPracticeResult } from '../types';

interface SynonymPracticeResultsProps { result: SynonymPracticeResult; onRetryIncorrect: () => void; onNewSession: () => void; onHome: () => void; hasIncorrect: boolean; }

export function SynonymPracticeResults({ result, onRetryIncorrect, onNewSession, onHome, hasIncorrect }: SynonymPracticeResultsProps) {
  const minutes = Math.floor(result.elapsedSeconds / 60);
  const seconds = result.elapsedSeconds % 60;
  const modeLabels = { 'multiple-choice': 'Chọn đáp án', matching: 'Nối cặp', 'select-all': 'Chọn tất cả', typing: 'Gõ đáp án' } as const;

  return (
    <section className="mx-auto max-w-3xl space-y-6">
      <div className="space-y-3 rounded-3xl border border-[#FCE7F3] bg-white p-6 text-center shadow-sm sm:p-8"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-[#FFF1F2] text-[#F472B6]"><Trophy className="h-8 w-8" aria-hidden="true" /></div><h1 className="text-xl font-extrabold text-[#4A4544] sm:text-2xl">Hoàn thành phiên ôn tập</h1><p className="text-xs text-[#77716F]">{modeLabels[result.mode]} đã hoàn tất. Đây là kết quả của bạn.</p><div className="grid grid-cols-2 gap-3 border-t border-[#FCE7F3] pt-4 sm:grid-cols-4"><div className="rounded-2xl border border-[#FCE7F3] bg-[#FFF9FA] p-3.5"><CheckCircle2 className="h-4 w-4 text-[#55A681]" aria-hidden="true" /><span className="mt-2 block text-[11px] font-bold text-[#A39A98]">Số câu đúng</span><span className="text-lg font-black text-[#4A4544]">{result.correctAnswers} / {result.totalQuestions}</span></div><div className="rounded-2xl border border-[#FCE7F3] bg-[#FFF9FA] p-3.5"><CheckCircle2 className="h-4 w-4 text-emerald-600" aria-hidden="true" /><span className="mt-2 block text-[11px] font-bold text-[#A39A98]">Độ chính xác</span><span className="text-lg font-black text-emerald-600">{result.scorePercentage}%</span></div><div className="rounded-2xl border border-[#FCE7F3] bg-[#FFF9FA] p-3.5"><Clock3 className="h-4 w-4 text-[#F472B6]" aria-hidden="true" /><span className="mt-2 block text-[11px] font-bold text-[#A39A98]">Thời gian</span><span className="text-sm font-extrabold text-[#5C635D]">{minutes > 0 ? `${minutes} phút ` : ''}{seconds} giây</span></div><div className="rounded-2xl border border-[#FCE7F3] bg-[#FFF9FA] p-3.5"><Trophy className="h-4 w-4 text-amber-500" aria-hidden="true" /><span className="mt-2 block text-[11px] font-bold text-[#A39A98]">Streak tốt nhất</span><span className="text-lg font-black text-amber-500">{result.bestStreak}</span></div></div></div>

      <div className="space-y-4 rounded-3xl border border-[#FCE7F3] bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-bold text-[#4A4544]"><CheckCircle2 className="h-4 w-4 text-[#F472B6]" aria-hidden="true" /> Danh sách từ đã ôn</h2><div className="divide-y divide-[#FCE7F3]">{result.answers.map((answer) => <div key={answer.vocabularyId} className="flex items-center justify-between gap-3 py-3 text-xs"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-extrabold text-[#4A4544]">{answer.word}</span><span className="text-[#A39A98]" aria-hidden="true">→</span><span className="font-bold text-[#D95476]">{answer.correctAnswers.join(', ')}</span></div>{answer.userAnswers.length > 0 && <p className="mt-1 truncate text-[#91898A]">Bạn trả lời: {answer.userAnswers.join(', ')}</p>}</div><span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-extrabold ${answer.isCorrect ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'}`}>{answer.isCorrect ? 'Đã thuộc' : 'Cần ôn'}</span></div>)}</div></div>

      <div className="flex flex-col gap-3 sm:flex-row"><button type="button" onClick={onRetryIncorrect} disabled={!hasIncorrect} className="flex-1 rounded-2xl border border-[#FCE7F3] bg-white py-3 text-xs font-extrabold text-[#5C635D] transition hover:bg-[#FFF9FA] disabled:cursor-not-allowed disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#F472B6]">Ôn lại câu sai</button><button type="button" onClick={onNewSession} className="flex-1 rounded-2xl bg-gradient-to-r from-[#F472B6] to-[#ED4F8E] py-3 text-xs font-extrabold text-white shadow-md shadow-pink-200 transition hover:opacity-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#F472B6]">Bắt đầu phiên mới</button><button type="button" onClick={onHome} className="flex-1 rounded-2xl bg-slate-100 py-3 text-xs font-extrabold text-[#5C635D] transition hover:bg-slate-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#F472B6]">Về trang tổng quan</button></div>
      {hasIncorrect && <div className="rounded-3xl border border-rose-100 bg-rose-50/50 p-5"><h3 className="flex items-center gap-2 text-sm font-bold text-rose-800"><XCircle className="h-4 w-4" aria-hidden="true" /> Câu cần xem lại</h3><div className="mt-3 space-y-2">{result.answers.filter((answer) => !answer.isCorrect).map((answer) => <div key={`wrong-${answer.vocabularyId}`} className="rounded-xl bg-white/80 p-3 text-xs"><span className="font-extrabold text-[#4A4544]">{answer.word}</span><span className="ml-2 font-bold text-emerald-700">{answer.correctAnswers.join(', ')}</span></div>)}</div></div>}
    </section>
  );
}
